version: '1.0'
services:
  rathole-server:
    image: archef2000/rathole:latest
    container_name: rathole
    environment:
      - "RUST_LOG=info"
      - "ADDRESS=0.0.0.0:2333"
      - "SERVICE_TOKEN_1=TOKEN_1"
      - "SERVICE_NAME_1=minecraft"
      - "SERVICE_ADDRESS_1=0.0.0.0:25565"
    restart: unless-stopped
    network_mode: host